### ISSUE TITLE
Sort out scripts

### ISSUE THREAD

**Issue by Fizzadar** [EDITD/kubetools#3]
The current thing is a mess downloading files from docs into home etc etc, why not use the power of Docker!

ie have a "copy database image" that simply runs and executes the copy DB stuff, ie:

```yml
dependencies:
  mariadb:
    containers:
      ...
      containerScripts:
        copy_production_database:
          image: docker-registry.edtd.net/database_copier:latest
          command: [./copy_production_database.sh]
```
