### ISSUE TITLE
Fix upgrade test condition false

### ISSUE THREAD

**Issue by Fizzadar** [EDITD/kubetools#56]
```yaml
upgrades:
  - name: Do something
    conditions:
      test: false
...
```

Isn't working - upgrade still runs under `ktd test`.
