### ISSUE TITLE
Rework/improve conditions

### ISSUE THREAD

**Issue by Fizzadar** [EDITD/kubetools#64]
Current conditions - these can control where deployments/dependencies/upgrades all run/exist:

```yaml
dev: true  # dev only, except where other conditions
test: true  # whether this is executed/needed during testing
envs:  []  # list of envs (clusters) this should be present in
namespaces: []  # list of namespaces this should be present in
notNamespaces: []  # list of namespaces this should *not* be present in
```

Ideally this should be less complex and less gotchas between combinations!

**Comment by Fizzadar** [comment]
Proposal:

```yaml
conditions:
  modes: [dev, test, deploy]  # (ktd up | ktd test | kubetools deploy)
  clusters:
    not: []
    match: ['*']
  namespaces:
    not: []
    match: ['*']
```

Essentially just a more explicit version of the current ones.

**Comment by gchazot** [comment]
* `clusters` is not consistent with `env` and `context`, as in, `kubetools` CLI expects
* I think `deploy` is the only mode where `clusters` and `namespaces` apply which makes it a bit asymmetrical
* More flexibility might be needed in the `deploy` case: One might want to specify "(cluster production AND namespace A) OR (cluster backup AND namespace B)" (as in, for example, NOT namespace B in cluster production, NOT namespace A in cluster backup, NOT namespace C in any cluster). This could be achieved with a list of `clusters` + `namespaces` pairs

**Comment by Fizzadar** [comment]
>     * `clusters` is not consistent with `env` and `context`, as in, `kubetools` CLI expects

Yeah this is a weird one really, `context` is a `(cluster, user)` tuple, but only the cluster bit of that is any concern to the app, the user bit really only relates to the place `kuebtools` is being executed from.

>     * I think `deploy` is the only mode where `clusters` and `namespaces` apply which makes it a bit asymmetrical

You're absolutely right, doesn't quite work!

>     * More flexibility might be needed in the `deploy` case: One might want to specify "(cluster production AND namespace A) OR (cluster backup AND namespace B)" (as in, for example, NOT namespace B in cluster production, NOT namespace A in cluster backup, NOT namespace C in any cluster). This could be achieved with a list of `clusters` + `namespaces` pairs

Interesting! So maybe we need to focus the conditions around the 'mode'. So, as default (everywhere/always):

```yaml
conditions:
  dev: true
  test: true
  deploy: true
```

Then limiting to clusters/namespaces could be:

```yaml
conditions:
  deploy:
    - ['production', 'A']
    - ['backup', 'B']
```

And finally the case where we want to deploy a dependency in all namespaces on the staging cluster but not elsewhere:

```yaml
conditions:
  deploy:
    - ['staging', '*']
```

This then removes the need for "not" matching because (I think?) everything can be achieved using the tuples with wildcard support.

**Comment by Fizzadar** [comment]
One question - is defaulting everything to `true` or `false` better? Leaning towards `true` as this is more common, and then conditions can be used to explicitly disable certain things in certain places.

Regarding backwards compatibility: it will be trivial to detect the old version `condition` object by the keys within, so we can keep the old style implementation in tandem.

**Comment by gchazot** [comment]
> One question - is defaulting everything to true or false better? Leaning towards true as this is more common, and then conditions can be used to explicitly disable certain things in certain places.

Definitely `true`. When reading a `kubetools.yml` you should expect that:
* all "modes" are the same
* everything you read is active

**unless otherwise specified explicitely**

**Comment by gchazot** [comment]
Instead of:

>
```yaml
conditions:
  deploy:
    - ['production', 'A']
    - ['backup', 'B']
```

I'd rather go explicit:
```yaml
conditions:
  deploy:
    - env: 'production'
      namespace: 'A'
    - env: 'backup'
      namespace: 'B'
```

Which opens up to negations and wildcards nicely:
```yaml
conditions:
  deploy:
    # namespace B in any environment but production
    - not_env: 'production'
      namespace: 'B'
    # Any namespace in backup environment
    - env: 'backup'  # Absence of `namespace` means `'*'`
```

And also opens backwards-compatible evolutions if later adding other conditions than `env` and `namespace`

**Comment by Fizzadar** [comment]
I like that a lot, definitely pro the explicitness!

One thing - we should sort out this mess of `env` vs `cluster` vs `context`. IMO we should go with `cluster`, as that's most appropriate (context is merely something the client uses to speak with a cluster). In tandem I also think we should populate `KUBE_CLUSTER` based on the context _cluster name_ when deploying (rather than just passing the context name as-is, because they might be different).

**Comment by Fizzadar** [comment]
Also, a thought for differentiating this from old configs:

```yaml
name: my-project
configVersion: 1
requireKubetools: '~=12.0'  # optional, replacement for minKubetoolsVersion
```
