### ISSUE TITLE
command/args pattern breaks for migrations

### ISSUE THREAD

**Issue by Jberrz** [EDITD/kubetools#85]
v13.0.0 (https://github.com/EDITD/kubetools/pull/83) breaks upgrade commands in the `kubetools.yml`. 

Running as:
```
upgrades:
  - name: Migrate database
    containerContext: webserver
    command: [flask, db, upgrade]
```
causes kubetools to interpret the command as an entrypoint instead of performing the migration. However running as:
```
upgrades:
  - name: Migrate database
    containerContext: webserver
    args: [flask, db, upgrade]
```
fails wth:
```
File ".../lib/python3.9/site-packages/kubetools/dev/environment.py", line 184, in up
    ' '.join(upgrade['command']),
'command' not found
```
